#!usr/bin/env python3
# -- coding: utf-8 --
#
# ------------------------------
# Name: Parsing_glam2scan_output -.
# Purpose:
# parse the glam2scan output
# Author: Maria del Carmen Sanchez
# USAGE: python gla2scan.txt glam2scan_fwd_out.txt
# Created: April,2023
# ------------------------------
import sys

glam2scan_out=sys.argv[1]
out_file=sys.argv[2]
with open(glam2scan_out,'r') as input_glam:
    for line in input_glam.readlines():
        line=line.strip()
        if line.startswith("/"):
            command_line=line
            command_line=command_line.split(" ")
            name_primer=command_line[3]
            name_primer=name_primer.split("_")
            name_primer=name_primer[0]
            direction=command_line[5]
            direction=direction.split(".")
            direction=direction[0]
        elif line.startswith('GLAM2SCAN'):
            pass
        elif line.startswith('Version 1056'):
            pass
        elif line.startswith("*"):
            pass
        else:
            line=line.split(' ')
            #print(line)
            if len(line) > 1:
                name_query=line[0]
                start=line[-5]
                #print(start)
                end=line[-3]
                strand=line[-2]
                score=line[-1]
                with open(out_file,'a') as out:
                    #print("%s\t%s\t%s\t%s\t%s\t%s\n"%(name_primer,start,end,strand,score,name_query))
                    out.write("%s\t%s\t%s\t%s\t%s\t%s\n"%(name_primer,start,end,strand,score,name_query))
